import type { Metadata } from "next"
import "../styles/globals.css"
import "@fortawesome/fontawesome-svg-core/styles.css"
import { config } from "@fortawesome/fontawesome-svg-core"

import { AppHeader, Transition } from "@/components/layouts"
import { AppProvider } from "@/components/providers/app"
import { jetbrainsMono } from "@/styles/fonts"

config.autoAddCss = false

export const metadata: Metadata = {
    title: "Nguyen Van Khai",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={jetbrainsMono.className}>
                <AppProvider>
                    <div className="min-h-screen flex flex-col px-4 md:px-48">
                        <AppHeader />
                        <div className="flex-grow pt-24 flex flex-col">
                            <Transition>{children}</Transition>
                        </div>
                    </div>
                </AppProvider>
            </body>
        </html>
    )
}
