import type { Metadata } from "next"
import { JetBrains_Mono } from "next/font/google"
import "./globals.css"
import Provider from "@/components/providers/Provider"
import Header from "@/components/app/Header"
import Transition from "@/components/app/Transition"
import { config } from "@fortawesome/fontawesome-svg-core"
import "@fortawesome/fontawesome-svg-core/styles.css"

config.autoAddCss = false
const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
})
export const metadata: Metadata = {
    title: "Nguyen Van Khai",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={jetbrainsMono.className}>
                <Provider>
                    <div className="min-h-screen px-4 md:px-48">
                        <Header />
                        <div className="pt-24">
                            <Transition>{children}</Transition>
                        </div>
                    </div>
                </Provider>
            </body>
        </html>
    )
}
